name: Test
on:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Do stuff that should fail
      run: ./fail.sh
