name: Test
on:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Do stuff that should fail
      run: ./fail.sh
    strategy:
      matrix:
        os:
        - ubuntu-latest
      fail-fast: false
